import Head from "next/head";
import { useEffect, useState } from "react";
import AudioTile from "../components/audio_tile";

const tiles = ["q", "w", "e", "a", "s", "d", "z", "x", "c"];

export default function Home() {
  const [globalVolume, setGlobalVolume] = useState(0.5);
  const registerKey = (key: string) => {
    const audio = document.getElementById(key) as HTMLAudioElement;
    audio && audio.play();
    // set element to active
    const button = document.getElementById(`button-${key}`);
    button && button.classList.add("active");
  };

  useEffect(() => {
    document.addEventListener("keydown", (e) => {
      if (tiles.includes(e.key)) {
        registerKey(e.key);
      }
    });
  }, [registerKey]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="flex flex-col items-center justify-center w-screen h-screen p-20 bg-neutral-900"
        onClick={() => {
          var audio = document.getElementById("x") as HTMLAudioElement;
          audio && audio.play();
        }}
      >
        <div className="flex flex-row flex-wrap items-center p-2 bg-white rounded-md justify-centerp-2">
          {tiles.map((tile) => (
            <AudioTile tile={tile} volume={globalVolume} />
          ))}
        </div>

        <section className="flex flex-col items-center justify-center w-screen h-screen mt-0 bg-neutral-900">
          <div className="flex flex-row flex-wrap items-center p-2 bg-white rounded-md justify-centerp-2">
            <input
              type="range"
              min="0"
              max="1"
              step="0.01"
              value={globalVolume}
              onChange={(e) => setGlobalVolume(parseFloat(e.target.value))}
            />
          </div>
        </section>
      </main>
    </>
  );
}
